/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.uber.api.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.uber.api.http.client.HttpContext;

/**
 * This is a model class for ErrorException type.
 */
public class ErrorException
        extends ApiException {
    private static final long serialVersionUID = -6353165003292077908L;
    private String code;
    private String message;
    private String fields;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public ErrorException(String reason, HttpContext context) {
        super(reason, context);
    }


    /**
     * Getter for Code.
     * @return Returns the String
     */
    @JsonGetter("code")
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for Code.
     * @param code Value for String
     */
    @JsonSetter("code")
    private void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("message")
    public String getMessage() {
        return this.message;
    }

    /**
     * Setter for Message.
     * @param message Value for String
     */
    @JsonSetter("message")
    private void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Fields.
     * @return Returns the String
     */
    @JsonGetter("fields")
    public String getFields() {
        return this.fields;
    }

    /**
     * Setter for Fields.
     * @param fields Value for String
     */
    @JsonSetter("fields")
    private void setFields(String fields) {
        this.fields = fields;
    }
}
