/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.uber.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Activity type.
 */
public class Activity {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String uuid;

    /**
     * Default constructor.
     */
    public Activity() {
    }

    /**
     * Initialization constructor.
     * @param  uuid  String value for uuid.
     */
    public Activity(
            String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for Uuid.
     * Unique identifier for the activity
     * @return Returns the String
     */
    @JsonGetter("uuid")
    public String getUuid() {
        return uuid;
    }

    /**
     * Setter for Uuid.
     * Unique identifier for the activity
     * @param uuid Value for String
     */
    @JsonSetter("uuid")
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Converts this Activity into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Activity [" + "uuid=" + uuid + "]";
    }

    /**
     * Builds a new {@link Activity.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Activity.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .uuid(getUuid());
        return builder;
    }

    /**
     * Class to build instances of {@link Activity}.
     */
    public static class Builder {
        private String uuid;



        /**
         * Setter for uuid.
         * @param  uuid  String value for uuid.
         * @return Builder
         */
        public Builder uuid(String uuid) {
            this.uuid = uuid;
            return this;
        }

        /**
         * Builds a new {@link Activity} object using the set fields.
         * @return {@link Activity}
         */
        public Activity build() {
            return new Activity(uuid);
        }
    }
}
