/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.uber.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Profile type.
 */
public class Profile {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String firstName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String lastName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String email;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String picture;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String promoCode;

    /**
     * Default constructor.
     */
    public Profile() {
    }

    /**
     * Initialization constructor.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  email  String value for email.
     * @param  picture  String value for picture.
     * @param  promoCode  String value for promoCode.
     */
    public Profile(
            String firstName,
            String lastName,
            String email,
            String picture,
            String promoCode) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.picture = picture;
        this.promoCode = promoCode;
    }

    /**
     * Getter for FirstName.
     * First name of the Uber user.
     * @return Returns the String
     */
    @JsonGetter("first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for FirstName.
     * First name of the Uber user.
     * @param firstName Value for String
     */
    @JsonSetter("first_name")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for LastName.
     * Last name of the Uber user.
     * @return Returns the String
     */
    @JsonGetter("last_name")
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for LastName.
     * Last name of the Uber user.
     * @param lastName Value for String
     */
    @JsonSetter("last_name")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for Email.
     * Email address of the Uber user
     * @return Returns the String
     */
    @JsonGetter("email")
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * Email address of the Uber user
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Picture.
     * Image URL of the Uber user.
     * @return Returns the String
     */
    @JsonGetter("picture")
    public String getPicture() {
        return picture;
    }

    /**
     * Setter for Picture.
     * Image URL of the Uber user.
     * @param picture Value for String
     */
    @JsonSetter("picture")
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * Getter for PromoCode.
     * Promo code of the Uber user.
     * @return Returns the String
     */
    @JsonGetter("promo_code")
    public String getPromoCode() {
        return promoCode;
    }

    /**
     * Setter for PromoCode.
     * Promo code of the Uber user.
     * @param promoCode Value for String
     */
    @JsonSetter("promo_code")
    public void setPromoCode(String promoCode) {
        this.promoCode = promoCode;
    }

    /**
     * Converts this Profile into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Profile [" + "firstName=" + firstName + ", lastName=" + lastName + ", email="
                + email + ", picture=" + picture + ", promoCode=" + promoCode + "]";
    }

    /**
     * Builds a new {@link Profile.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Profile.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .firstName(getFirstName())
                .lastName(getLastName())
                .email(getEmail())
                .picture(getPicture())
                .promoCode(getPromoCode());
        return builder;
    }

    /**
     * Class to build instances of {@link Profile}.
     */
    public static class Builder {
        private String firstName;
        private String lastName;
        private String email;
        private String picture;
        private String promoCode;



        /**
         * Setter for firstName.
         * @param  firstName  String value for firstName.
         * @return Builder
         */
        public Builder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Setter for lastName.
         * @param  lastName  String value for lastName.
         * @return Builder
         */
        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for picture.
         * @param  picture  String value for picture.
         * @return Builder
         */
        public Builder picture(String picture) {
            this.picture = picture;
            return this;
        }

        /**
         * Setter for promoCode.
         * @param  promoCode  String value for promoCode.
         * @return Builder
         */
        public Builder promoCode(String promoCode) {
            this.promoCode = promoCode;
            return this;
        }

        /**
         * Builds a new {@link Profile} object using the set fields.
         * @return {@link Profile}
         */
        public Profile build() {
            return new Profile(firstName, lastName, email, picture, promoCode);
        }
    }
}
