/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.uber.api.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.uber.api.UberAPIClient;
import com.uber.api.exceptions.ApiException;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class UserControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static UberAPIClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static UserController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getUserController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * The User Profile endpoint returns information about the Uber user that has authorized with
     * the application.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestUserProfile() throws Exception {

        // Set callback and perform API call
        try {
            controller.userProfile();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * The User Activity endpoint returns data about a user's lifetime activity with Uber. The
     * response will include pickup locations and times, dropoff locations and times, the distance
     * of past requests, and information about which products were requested.<br><br>The history
     * array in the response will have a maximum length based on the limit parameter. The response
     * value count may exceed limit, therefore subsequent API requests may be necessary.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestUserActivity() throws Exception {
        // Parameters for the API call
        Integer offset = null;
        Integer limit = null;

        // Set callback and perform API call
        try {
            controller.userActivity(offset, limit);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

}
